---
# tasks file for roles/checkinaddr

- name: Check DHCP Scope
  include_role: 
    name: getdhcpscope
    
- name: Checking in a SingleIP
  uri:
    url: http://10.1.20.6:81/addr/checkin?address={{scope_result}}
    method: DELETE
    headers:
      Content-Type: application/json
    body_format: json
    status_code: 404, 200
  when: scopestate.json.IPAddress.IPAddressToString is defined
  ignore_errors: yes

- name: Checking in IP Multiple Addresses
  uri:
    url: http://10.1.20.6:81/addr/checkin?address={{item}}
    method: DELETE
    headers:
      Content-Type: application/json
    body:
      username: "{{ provider.user }}"
      password: "{{ provider.password }}"
    body_format: json
    status_code: 404, 200
  loop: "{{ scope_result }}"
  ignore_errors: yes