---
# tasks file for roles/delete.iisserver

- name: DELETE AD A Record
  uri:
    url: http://10.1.20.6:81/dns
    method: DELETE
    headers:
      Content-Type: application/json
    body: "{{ lookup('template','templates/a-record.j2', split_lines=False )}}"
    body_format: json
    status_code: 404, 200
  when: iis_address is defined  

- name: Delete AD delegation account
  uri:
    url: http://10.1.20.6:81/user
    method: DELETE
    headers:
      Content-Type: application/json
    body: "{{ lookup('template','templates/user.j2', split_lines=False )}}"
    body_format: json
    status_code: 200

- name: Delete SPN 
  uri:
    url: http://10.1.20.6:81/computer
    method: DELETE
    headers:
      Content-Type: application/json
    body: 
      computer: "IIS"
      spn: "HTTP/{{dns_name}}"
    body_format: json
    status_code: 200

- name: Delete Website
  uri:
    url: http://10.1.20.6:81/website
    method: DELETE
    headers:
      Content-Type: application/json
    body: 
      site_name: "{{dns_name}}"
    body_format: json
    status_code: 200

