---
# tasks file for roles/deleteldap_aaa

- name: Delete Kerberos APM LDAP
  uri:
    url: https://{{bigip}}/mgmt/tm/apm/aaa/ldap/~{{partition_name}}~{{vs_name}}-ldap-servers
    method: DELETE
    headers:
      X-F5-Auth-Token: "{{ f5_auth_token }}"
    validate_certs: false
  delegate_to: localhost
  ignore_errors: true